import { Task, TaskPriority, TaskStatus } from '../types';
import { generateId } from './helpers';

export const mockTasks: Task[] = [
  {
    id: generateId(),
    title: 'Design new landing page',
    description: 'Create wireframes and high-fidelity mockups for the new landing page. Focus on conversion optimization and modern design trends.',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['design', 'ui/ux', 'high-priority'],
    assignee: 'Sarah Johnson',
    estimatedHours: 16,
  },
  {
    id: generateId(),
    title: 'Implement user authentication',
    description: 'Set up JWT-based authentication with refresh tokens. Include email verification and password reset functionality.',
    status: 'in-progress',
    priority: 'urgent',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['backend', 'security', 'authentication'],
    assignee: 'Mike Chen',
    estimatedHours: 24,
  },
  {
    id: generateId(),
    title: 'Write API documentation',
    description: 'Document all REST API endpoints using OpenAPI/Swagger specification. Include request/response examples and authentication details.',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['documentation', 'api'],
    assignee: 'Alex Rivera',
    estimatedHours: 8,
  },
  {
    id: generateId(),
    title: 'Fix mobile responsive issues',
    description: 'Address layout breaking on mobile devices, especially on screens smaller than 375px. Test on various devices.',
    status: 'todo',
    priority: 'high',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['frontend', 'bug', 'responsive'],
    estimatedHours: 6,
  },
  {
    id: generateId(),
    title: 'Database optimization',
    description: 'Analyze and optimize slow queries. Add indexes where necessary and consider query result caching.',
    status: 'review',
    priority: 'medium',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['backend', 'performance', 'database'],
    assignee: 'Jordan Lee',
    estimatedHours: 12,
  },
  {
    id: generateId(),
    title: 'Setup CI/CD pipeline',
    description: 'Configure automated testing and deployment using GitHub Actions. Include staging and production environments.',
    status: 'completed',
    priority: 'high',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ['devops', 'automation', 'deployment'],
    assignee: 'Taylor Smith',
    estimatedHours: 16,
  },
  {
    id: generateId(),
    title: 'Conduct user testing',
    description: 'Plan and execute user testing sessions with 10-15 participants. Collect feedback and create actionable insights.',
    status: 'todo',
    priority: 'low',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    tags: ['research', 'ux', 'testing'],
    estimatedHours: 20,
  },
  {
    id: generateId(),
    title: 'Update dependencies',
    description: 'Review and update all project dependencies. Test thoroughly to ensure no breaking changes.',
    status: 'completed',
    priority: 'low',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    tags: ['maintenance', 'dependencies'],
    estimatedHours: 4,
  },
];

export const createTask = (
  title: string,
  description: string = '',
  priority: TaskPriority = 'medium',
  status: TaskStatus = 'todo'
): Task => {
  return {
    id: generateId(),
    title,
    description,
    status,
    priority,
    dueDate: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: [],
  };
};
